<a href="https://colab.research.google.com/github/suneelshrestha/ML_from_scratch/blob/main/numpybasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy Basics


*   Creating array
*   Indexing
*   Slicing
*   reshape
*   manupulation
*   search
*   filter
*   sort



## Creating array


In [15]:
import numpy as np

#creating numpy array based on our input elem
arr = np.array([1,2,3])

print(arr)

[1 2 3]


In [20]:
#creating multiple rows and cols
arr = np.array([(1,2,3),(4,5,6)])

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [23]:
#creating array with all zeros
#this will create float arrays
arr = np.zeros((3,3))

#this will create int type array
arr1 = np.zeros((3,3),dtype=int)

print(arr)
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [24]:
#create array with ones
arr = np.ones((3,3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
#create an array with specific element only
arr = np.full((3,4),5)

print(arr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [26]:
#create identity array
arr = np.eye((5))
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##random array


In [96]:
#create a random array
#this will create array of size in the float and in the range of 0 to 1
arr = np.random.rand(4,5)
print(arr)


#the seed will make the element same every time
arr = np.random.seed(80)
arr = np.random.random((4,5))

print(arr)

[[0.63777353 0.63784599 0.14176518 0.35566774 0.51365124]
 [0.22176798 0.70747525 0.43383946 0.11841143 0.0081044 ]
 [0.77802056 0.71868497 0.85399514 0.05228477 0.34057066]
 [0.73234244 0.28141507 0.44264103 0.33531462 0.09480884]]
[[0.52191572 0.69940637 0.26986897 0.67448187 0.90807208]
 [0.6851502  0.21165334 0.31726607 0.2672994  0.12050632]
 [0.9968569  0.08043969 0.28459975 0.5352502  0.84580211]
 [0.20012414 0.81204355 0.37293679 0.80964124 0.01199526]]


In [95]:
#create a random array with int value
arr = np.random.randint(10,90,(4,5))

print(arr)

[[49 61 60 56 19]
 [34 34 11 27 64]
 [26 51 30 41 34]
 [77 18 56 77 36]]


In [77]:
#create array with specifci range and specific element
#that means make array of range 0,10,no_of_element_or_half

#this will devide the range in 7 parts
arr = np.linspace(0,10,7,dtype=int)

print(arr)

[ 0  1  3  5  6  8 10]


In [78]:
#creating array fo specific range with specific diff
#this will create the array element possible from 1 to 90 with difference with 10
arr = np.arange(1,90, 10)

print(arr)

[ 1 11 21 31 41 51 61 71 81]


In [83]:
#conver the list to the nparray
list1 = [1,2,3,4,5]
print("list: ",list1)
print(type(list1))

#convet the list to np array

arr = np.asarray(list1)
print("\nafter coveting")
print("list: ",arr)
print(type(arr))

list:  [1, 2, 3, 4, 5]
<class 'list'>

after coveting
list:  [1 2 3 4 5]
<class 'numpy.ndarray'>


## indexing
reading the value from the specific index and put value in that place etx

In [31]:
#reading the value from speicifc index
arr = np.array([1,2,3,4,5,6])

#reading the value from the index 4
print(arr[4])

5


In [35]:
#replaicng the value in the spcific index
arr = np.array([1,2,3,4,5])
print("before replacing: ",arr)

#replace the value in index 4
arr[2]=58
print("before replacing: ",arr)

before replacing:  [1 2 3 4 5]
before replacing:  [ 1  2 58  4  5]


## slicing
In this slicing we will slice the array form certain index

In [41]:
#read the array from the specific index
arr = np.array([1,2,3,4,5,6])

#print the element from the beginning to the index of the 4
print(arr[:4])

#print the element from the index 1 to the index of the 4
print(arr[1:4])

#print the element from the index 1 to the last index
print(arr[3:])

[1 2 3 4]
[2 3 4]
[4 5 6]


## reshape
here we will find the shape of the array and reshapre them

In [53]:
#print the shape of the array
arr = np.array([1,2,3,4])

#the shape will be 2,3 that is two rows and three columns
arr = np.array([(91,2,3),(5,6,7)])
print("before reshape: ")
print(arr.shape)
print(arr)

#now reshape the array
newarr=arr.reshape(3,2)
print("\nafter reshape")
print(newarr.shape)
print(newarr)

before reshape: 
(2, 3)
[[91  2  3]
 [ 5  6  7]]

after reshape
(3, 2)
[[91  2]
 [ 3  5]
 [ 6  7]]


##iterating through the element of the array


In [60]:
#iterate through each element in array

arr = np.array([1,2,3,4,5])
arr1 = np.array([[1,2,3,4],[4,5,6,7]])

#this will print all the element in the array
for char in arr1:
  print(arr1)

[[1 2 3 4]
 [4 5 6 7]]
[[1 2 3 4]
 [4 5 6 7]]


In [62]:
#create new copy from the existing array

arr = np.array([1,2,3,4,5])
new_arr = arr.copy()
print(new_arr)


[1 2 3 4 5]


In [63]:
#reverse array
arr = np.array([1,2,3,4,5])
rev = np.flip(arr)

print(rev)

[5 4 3 2 1]


## searching sorting

In [71]:
#search the value in the array

arr = np.array([1,2,3,4,5,2])

#give the index of the value 3
x = np.where(arr == 3)
print(x)

#give the index of the element that is even
x = np.where(arr % 2 == 0)
print(x)
#print the even no from the provide index
print(arr[x])

#find the index of the element we want to find
y = np.searchsorted(arr,5)
print(y)

(array([2]),)
(array([1, 3, 5]),)
[2 4 2]
6


In [70]:
# sorting array
arr = np.array([9,4,7,2,4,1])
print(np.sort(arr))

[1 2 4 4 7 9]


In [73]:
# split the array
arr = np.array([1,2,3,4,5])
print(np.array_split(arr,3))

[array([1, 2]), array([3, 4]), array([5])]
